version: '3.8'

services:
  script-assistant:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # 如果需要后端API服务
  # api:
  #   build: ./api
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped
